INSERT INTO conservation_db.decision_name(dsc_name) VALUES ('للإعداد');
INSERT INTO conservation_db.decision_name(dsc_name) VALUES ('مسجل لحساب الوكالة العقارية');
INSERT INTO conservation_db.decision_name(dsc_name) VALUES ('مسجل لحساب البلدية');
INSERT INTO conservation_db.decision_name(dsc_name) VALUES ('مسجل لحساب أملاك الدولة');
INSERT INTO conservation_db.decision_name(dsc_name) VALUES ('مسجل لحساب OPGJ');
INSERT INTO conservation_db.decision_name(dsc_name) VALUES ('غير مدرج');
INSERT INTO conservation_db.decision_name(dsc_name) VALUES ('مسجل لحساب شخص طبيعي');
INSERT INTO conservation_db.decision_name(dsc_name) VALUES ('تحقيق في وضعية المالك الحقيقي');
INSERT INTO conservation_db.decision_name(dsc_name) VALUES ('تصحيح مساحة');
INSERT INTO conservation_db.decision_name(dsc_name) VALUES ('طلب تحديد عقار');
INSERT INTO conservation_db.decision_name(dsc_name) VALUES ('طلب ترقيم عقار');
INSERT INTO conservation_db.decision_name(dsc_name) VALUES ('طلب بطاقة عقارية');
INSERT INTO conservation_db.decision_name(dsc_name) VALUES ('تسوية المساحة الزائدة الوكالة العقارية');
INSERT INTO conservation_db.decision_name(dsc_name) VALUES ('تسوية المساحة الزائدة أملاك الدولة');
INSERT INTO conservation_db.decision_name(dsc_name) VALUES ('تسوية المساحة الزائدة البلدية');
INSERT INTO conservation_db.decision_name(dsc_name) VALUES ('للتحقق مع المعني');
INSERT INTO conservation_db.decision_name(dsc_name) VALUES ('للدراسة مع المحافظ');
INSERT INTO conservation_db.decision_name(dsc_name) VALUES ('مؤقت سنتين');
INSERT INTO conservation_db.decision_name(dsc_name) VALUES ('مؤقت 04 اشهر');
INSERT INTO conservation_db.decision_name(dsc_name) VALUES ('مسجل في حساب العقارات غير المطالب بها');
